### PR TITLE
fix(animation): React to updated height properly

### LINKED ISSUE #29: [Request] Respond to height updates during animations
As said in #28, animating and changing height at the same time is not working properly. Do you think this is fixable, or this is by design from that library and cannot change?

Do you need a reproduction? 

Thank you so much for the lib and your time :)

### PR DESCRIPTION
**Pull request by Titozzz**
fixes #29

### CODE REVIEW

File: src/react-collapsed.js [hunk 1]
```diff
@@ -86,6 +86,8 @@ export default function useCollapse(initialConfig = {}) {
       // it's safe to clear all style overrides
       if (height === styles.height) {
         setStyles({});
+      } else {
+        setStyles({height});
```
Comment (roginfarrer) [inline src/react-collapsed.js]: We should combine this height property with the the current styles, otherwise we lose the transition timing function and all that. 

```suggestion
        setStyles(oldStyles => ({...oldStyles, height}));
```

File: src/react-collapsed.js [hunk 2]
```diff
@@ -86,6 +86,8 @@ export default function useCollapse(initialConfig = {}) {
       // it's safe to clear all style overrides
       if (height === styles.height) {
         setStyles({});
+      } else {
```
Comment (roginfarrer) [inline src/react-collapsed.js]: Let's add a comment describing why this `else` block is needed. Something like this would be good:

```suggestion
      } else {
      // If the heights don't match, this could be due the height of the content changing mid-transition
      // If that's the case, re-trigger the animation to animate to the new height
```

**Comment by Titozzz** [comment]
Cool, all good now :)
